### PR TITLE
fix rounding issues to avoid error

### PR DESCRIPTION
**Pull request by joostwaaijer**
Using the same check as the base omnipay package created by craftcms: https://github.com/craftcms/commerce-omnipay/blob/develop/src/base/Gateway.php#L754

### CODE REVIEW

**Comment by boboldehampsink** [comment]
@WHITE-developer any chance of merging this?

**Comment by white-lukas** [comment]
Should already be fixed by https://github.com/white-nl/commerce-mollie-plus/commit/0edf35293913526f232c570c2d5d7ba5994eb866

**Comment by boboldehampsink** [comment]
@white-lukas cool, any chance of release soon?

**Comment by white-lukas** [comment]
just released `2.5.0`

**Pull request closed without merging**
